In [1]:
import nupic
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd

In [28]:
data = pd.read_csv('/home/devashish/Desktop/Activity Recognition from Single Chest-Mounted Accelerometer/1.csv')

In [29]:
pd.set_option('display.max_columns', 80) 
data.head(10)

   Time  Acc1  Acc2  Acc3  Activity
0     0  1502  2215  2153         1
1     1  1667  2072  2047         1
2     2  1611  1957  1906         1
3     3  1601  1939  1831         1
4     4  1643  1965  1879         1
5     5  1604  1959  1921         1
6     6  1640  1829  1940         1
7     7  1607  1910  1910         1
8     8  1546  2045  1910         1
9     9  1529  2049  1972         1

In [30]:
data.sample(frac=1)

          Time  Acc1  Acc2  Acc3  Activity
43073    43073  1883  2467  2061         4
58594    58594  1897  2325  2053         4
157394  157390  1926  2404  2077         7
63291    63291  1882  2319  2130         4
94017    94017  1871  2379  2017         7
25320    25320  1958  2382  2096         1
6514      6514  1967  2374  2119         1
16596    16596  1987  2366  2127         1
88364    88364  1876  2381  1990         7
47717    47717  1852  2570  2012         4
71866    71866  1903  2283  2113         5
31261    31261  1965  2369  2137         1
1583      1583  1973  2363  2093         1
84129    84129  1943  2380  2018         7
92735    92735  1883  2381  1988         7
37154    37154  1917  2389  2036         3
26332    26332  1970  2377  2101         1
12617    12617  1952  2376  2109         1
132488  132490  1909  2384  1996         7
49802    49802  1881  2289  2036         4
64592    64592  1978  2390  2122         4
13116    13116  1960  2373  2118         1
109052  109050  1906  2386  1971         7
148600  148600  1898  2399  2040         7
128990  128990  1906  2387  1989         7
137053  137050  1899  2383  1961         7
14624    14624  1969  2371  2125         1
111446  111450  1910  2386  1966         7
55354    55354  1900  2321  2035         4
6074      6074  1962  2377  2109         1
...        ...   ...   ...   ...       ...
24860    24860  1952  2382  2091         1
118056  118060  1908  2384  1981         7
128351  128350  1913  2385  1997         7
155309  155310  1910  2374  2114         7
104494  104490  1896  2383  1992         7
35095    35095  1882  2383  2027         3
155847  155850  1929  2381  2102         7
143293  143290  1902  2379  1980         7
82029    82029  1915  2388  2041         7
21072    21072  1967  2375  2124         1
99858    99858  1911  2385  1995         7
85325    85325  1884  2387  1986         7
85734    85734  1919  2376  1985         7
32949    32949  1950  2358  2177         1
162023  162020  1904  2381  2087         7
127005  127000  1915  2383  2004         7
74458    74458  1890  2388  1992         3
29953    29953  1966  2365  2133         1
55007    55007  1988  2411  2118         4
12768    12768  1967  2379  2117         1
75471    75471  1883  2376  1978         3
28797    28797  1970  2367  2138         1
117900  117900  1903  2390  1986         7
97974    97974  1905  2384  1989         7
72014    72014  1965  2372  2087         5
89451    89451  1881  2376  1992         7
54348    54348  1887  2239  1992         4
78738    78738  1914  2374  2104         6
134756  134760  1889  2382  1974         7
17867    17867  1978  2378  2130         1

[162501 rows x 5 columns]

In [31]:
data.sort_values('Time')

          Time  Acc1  Acc2  Acc3  Activity
0            0  1502  2215  2153         1
1            1  1667  2072  2047         1
2            2  1611  1957  1906         1
3            3  1601  1939  1831         1
4            4  1643  1965  1879         1
5            5  1604  1959  1921         1
6            6  1640  1829  1940         1
7            7  1607  1910  1910         1
8            8  1546  2045  1910         1
9            9  1529  2049  1972         1
10          10  1637  1978  1945         1
11          11  1596  2046  1866         1
12          12  1590  2006  1978         1
13          13  1601  1966  1957         1
14          14  1542  2003  1959         1
15          15  1598  2027  1941         1
16          16  1511  2258  1983         1
17          17  1555  1980  2023         1
18          18  1508  2468  1934         1
19          19  1580  1697  2005         1
20          20  1627  2073  1992         1
21          21  1592  2130  2063         1
22          22  1634  2088  1991         1
23          23  1638  2102  1916         1
24          24  1593  2123  1948         1
25          25  1542  2133  2034         1
26          26  1601  2015  2042         1
27          27  1613  1938  1936         1
28          28  1644  1974  2000         1
29          29  1642  1933  2046         1
...        ...   ...   ...   ...       ...
162472  162470  1926  2382  2071         7
162473  162470  1924  2382  2075         7
162474  162470  1923  2385  2071         7
162470  162470  1925  2380  2075         7
162485  162480  1930  2384  2077         7
162481  162480  1931  2384  2079         7
162484  162480  1928  2383  2077         7
162483  162480  1924  2384  2077         7
162482  162480  1930  2382  2075         7
162480  162480  1930  2383  2076         7
162478  162480  1932  2384  2080         7
162477  162480  1925  2385  2070         7
162476  162480  1924  2383  2083         7
162475  162480  1921  2383  2079         7
162479  162480  1924  2385  2081         7
162494  162490  1931  2386  2073         7
162493  162490  1932  2383  2072         7
162492  162490  1931  2388  2076         7
162491  162490  1927  2383  2079         7
162490  162490  1931  2383  2076         7
162488  162490  1925  2383  2079         7
162487  162490  1928  2385  2077         7
162486  162490  1929  2386  2076         7
162489  162490  1931  2386  2073         7
162499  162500  1926  2385  2078         7
162495  162500  1926  2382  2072         7
162496  162500  1927  2388  2074         7
162497  162500  1930  2383  2074         7
162498  162500  1929  2385  2076         7
162500  162500  1922  2387  2078         0

[162501 rows x 5 columns]